<?php
namespace app\controllers;

use app\services\PayService;
use yii\rest\ActiveController;

class PayController extends ActiveController
{
    public $modelClass =  PayService::class;

//    public function actions()
//    {
//        return parent::actions(); // TODO: Change the autogenerated stub
//    }

}